---
title: "Publications"
---
<link rel="stylesheet" href="styles.css" type="text/css">
<link rel="stylesheet" href="academicons-1.8.6/css/academicons.min.css"/>
<br>

## Peer-reviewed Articles

Nunez Y, **Gibson EA**, Tanner EM, Gennings C, Coull BA, Goldsmith JA, Kioumourtzoglou M-A. Reflection on modern methods: Good practices for applied statistical learning in epidemiology. International Journal of Epidemiology. 2021 Jan 9. [<i class="far fa-file-pdf"></i>](papers/nunez_ije.pdf){target="_blank"} 

**Gibson EA**, Nunez Y, Abuawad A, Zota AR, Renzetti S, Devick KL, Gennings C, Goldsmith J, Coull BA, Kioumourtzoglou M-A. An overview of methods to address distinct research questions on environmental mixtures: an application to persistent organic pollutants and leukocyte telomere length. Environmental Health. 2019 Dec 1; 18(1): 76. [<i class="far fa-file-pdf"></i>](papers/gibson_eh.pdf){target="_blank"} 

Chen Y, Wu F, Liu X, Parvez F, LoIacono NJ, **Gibson EA**, Kioumourtzoglou M-A, Levy D, Shahriar H, Uddin MN, Islam T, Lomax A, Saxenad R, Sanchez T, Santiago D, Ellis T, Ahsan H, Wasserman, GA, Graziano JH. Early life and adolescent arsenic exposure from drinking water and blood pressure in adolescence. Environmental Research. 2019 Aug 20:108681. [<i class="far fa-file-pdf"></i>](papers/chen_er.pdf){target="_blank"} 

**Gibson EA**, Goldsmith J, Kioumourtzoglou M-A. Complex Mixtures, Complex Analyses: an Emphasis on Interpretable Results. Current Environmental Health Reports. 2019 May 8:1-9. [<i class="far fa-file-pdf"></i>](papers/gibson_cehr.pdf){target="_blank"} 

**Gibson EA**, Stapleton HM, Calero L, Holmes D, Burke K, Martinez R, Cortes B, Nematollahi A, Evans D, Anderson KA, Herbstman JB. Differential exposure to organophosphate flame retardants in mother-child pairs. Chemosphere. 2018 Dec 4; 219: 567-73. [<i class="far fa-file-pdf"></i>](papers/gibson_chemo.pdf){target="_blank"} 

**Gibson EA**, Siegel EL, Eniola F, Herbstman JB, Factor-Litvak P. Effects of polybrominated diphenyl ethers on child cognitive, behavioral, and motor development. International Journal of Environmental Research and Public Health. 2018 Aug 2; 15(8): 1636. [<i class="far fa-file-pdf"></i>](papers/gibson_ijerph.pdf){target="_blank"} 

**Gibson EA**, Stapleton HM, Calero L, Holmes D, Burke K, Martinez R, Cortes B, Nematollahi A, Evans D, Herbstman JB. Flame retardant exposure assessment: findings from a behavioral intervention study. Journal of Exposure Science & Environmental Epidemiology. 2018 Jun 28: 1. [<i class="far fa-file-pdf"></i>](papers/gibson_jesee.pdf){target="_blank"} 

Wasserman GA, Liu X, Parvez F, Chen Y, Factor-Litvak P, LoIacono NJ, Levy D, Shahriar H, Uddin MN, Islam T, Lomax A, Saxena R, **Gibson EA**, Kioumourtzoglou M-A, Balac O, Sanchez T, Kline JK, Santiago D, Ellis T, van Geen A, Graziano JH. A cross-sectional study of water arsenic exposure and intellectual function in adolescence in Araihazar, Bangladesh. Environment International. 2018 Sep 30; 118: 304-13. [<i class="far fa-file-pdf"></i>](papers/wasserman.pdf){target="_blank"} 

Lane K, Ito K, Johnson S, **Gibson EA**, Tang A, Matte T. Burden and risk factors for cold-related illness and death in New York City. International Journal of Environmental Research and Public Health. 2018 Mar 30; 15(4): 632. [<i class="far fa-file-pdf"></i>](papers/lane.pdf){target="_blank"} 

<br>

## Presentations

**Gibson EA**. Bayesian non-parametric non-negative matrix factorization for identifying patterns in environmental mixtures. Oral presentation for the National Institute of Environmental Health Sciences (NIEHS) Powering Research Through Innovative Methods for Mixtures in Epidemiology (PRIME) Program Meeting. October 2020. Virtual. [<i class="far fa-file-pdf"></i>](papers/gibson_prime.pdf){target="_blank"}

**Gibson EA**, Goldsmith J, Perera F, Factor-Litvak P, Paisley J, Herbstman JB, Kioumourtzoglou M-A. Identifying patterns in environmental mixtures: a Bayesian approach & application to endocrine disrupting chemicals. Discussion poster presentation for the International Society for Environmental Epidemiology (ISEE). August 2020. Virtual. [<i class="far fa-file-pdf"></i>](papers/isee_2020_gibson.pdf){target="_blank"}

**Gibson EA**, Yan J, Colgan R, Chillrud L, Wright J, Goldsmith J, Kioumourtzoglou M-A. Principal Component Pursuit for pattern identification in environmental health. Oral presentation for the American Statistical Association's (ASA Joint Statistical Meetings (JSM). August 2020. Virtual. [<i class="far fa-file-pdf"></i>](papers/jsm_2020.pdf){target="_blank"}

**Gibson EA**, Herbstman JB, Kioumourtzoglou M-A. Complex chemical mixtures in environmental epidemiology. Oral presentation for Seminar Series, Environmental Health Sciences Department (EHS), Mailman School of Public Health (MSPH), Columbia University. Oct 2019. New York, NY, USA. [<i class="far fa-file-pdf"></i>](papers/EHS_Seminar_Oct_7.pdf){target="_blank"}

**Gibson EA**, Spratlen MJ, Colgan R, Wright J, Goldsmith J, Perera FP, Factor-Litvak P, Herbstman JB, Kioumourtzoglou M-A. Patterns of phenol, paraben & phthalate exposure in NYC women. Poster presentation for the International Society for Environmental Epidemiology (ISEE). August 2019. Utrecht, Netherlands. [<i class="far fa-file-pdf"></i>](papers/niehs_pcp_poster.pdf){target="_blank"} 

**Gibson EA**, Nunez Y, Kioumourtzoglou M-A. Overview of Commonly-Used Methods to Analyze Exposure to Mixtures in Environmental Epidemiology. Poster presentation for the NIEHS PRIME Program Meeting. April 2019. Research Triangle Park, NC, USA. [<i class="far fa-file-pdf"></i>](papers/NIEHS_PRIME_Overview.pdf){target="_blank"}  | [Code](https://github.com/lizzyagibson/NIEHS-PRIME-Overview-Poster)

**Gibson EA**, Spratlen MJ, Colgan R, Wright J, Goldsmith J, Perera FP, Factor-Litvak P, Herbstman JB, Kioumourtzoglou M-A. Patterns of phenol, paraben & phthalate exposure in NYC women. Poster presentation for the NIEHS PRIME Program Meeting. April 2019. Research Triangle Park, NC, USA. [<i class="far fa-file-pdf"></i>](papers/niehs_pcp_poster.pdf){target="_blank"} 

**Gibson EA**, Kioumourtzoglou M-A, Herbstman JB. Environmental mixtures of endocrine disrupting chemicals and risk to cognitive development. Oral presentation for the American Pediatric Association (APA) Environmental Health Scholars Retreat. October 2018. Providence, Rhode Island, USA.

**Gibson EA**, Kioumourtzoglou M-A, Wasserman GA, Liu X, Parvez F, Chen Y, Factor-Litvak P,  LoIacono NJ, Shahriar H, Nasir Uddin M, Islam T, Saxena R, Balac O, Sanchez T, Kline JK, van Geen A, Graziano JH. Metal Exposure as a Mixture and Intellectual Function in Adolescence in Bangladesh. Poster presentation for the International Society for Environmental Epidemiology (ISEE). August 2018. Ottawa, Ontario, Canada.

**Gibson EA**, Stapleton HM, Calero L, Holmes D, Burke K, Martinez R, Cortes B, Nematollahi A, Evans D, Anderson KA, Herbstman JB. Flame Retardant Exposure Assessment: Findings from a Behavioral Intervention. Oral presentation for the Brominated Flame Retardant Workshop (BFR). May 2018. Niagara-on-the-lake, Ontario, Canada.

**Gibson EA**, Stapleton HM, Calero L, Holmes D, Burke K, Martinez R, Cortes B, Nematollahi A, Evans D, Anderson KA, Herbstman JB. Intervention efficacy: Differentiating signal from noise. Oral presentation for the International Society for Children’s Health and the Environment (ISCHE). August 2016. Whidbey Island, Washington, USA.

**Gibson EA**, Stapleton HM, Calero L, Holmes D, Burke K, Martinez R, Cortes B, Nematollahi A, Evans D, Anderson KA, Herbstman JB. Reducing exposure to flame retardants. Does it work? Oral presentation for Seminar Series, Environmental Health Sciences Department (EHS), Mailman School of Public Health (MSPH), Columbia University. May 2017. New York, NY, USA.

**Gibson EA**, Zhou Z, Factor-Litvak P, Perera F, Yu J, Tang D. Molecular effects of in utero cadmium exposure. Poster presentation for the International Society for Environmental Epidemiology (ISEE). August 2016. Rome, Italy.

Lane K, Ito K, Johnson S, **Gibson EA**, Tang A, Matte T. Investigation of Cold-Related Deaths in New York City, 2009-2015. Poster presentation for the Summit on Environmental Hazards and Health Effects, CDC National Center for Environmental Health. January 2016. Atlanta, GA, USA.

**Gibson EA**, Zhou Z, Factor-Litvak P, Perera F, Yu J, Tang D. Molecular effects of in utero cadmium exposure. Oral presentation for Master’s Student Day, Epidemiology Department, Mailman School of Public Health (MSPH), Columbia University. October 2015. New York, NY, USA.

